"Pachuca": {
    torneo: "Clausura 2026 · J1–J12",
    status: "real",
    record: { G:8, E:3, P:1, pts:27, pj:12, gf:35, gc:5 },
    local:  { G:5, E:1, P:0, pts:16, pj:6,  gf:21, gc:2 },
    visita: { G:3, E:2, P:1, pts:11, pj:6,  gf:14, gc:3 },
    primeGol: { favor:"8V 2E 0D (anota 24')", contra:"0V 1E 1D (recibe 26')" },
    minPGF: 24, minPGC: 26,
    subsPorPartido: 4.2,
    formaciones: [
      { form:"1-4-4-2",   pj:9, v:6, e:2, d:1, pts:20, gf:27, gc:4, contexto:"Sistema base · bloque sólido y transición rápida" },
      { form:"1-4-2-3-1", pj:2, v:1, e:0, d:1, pts:3,  gf:7,  gc:1, contexto:"Vs rivales que disputan el mediocampo · Cruz Azul y Necaxa" },
      { form:"1-4-4-1-1", pj:1, v:0, e:1, d:0, pts:1,  gf:2,  gc:2, contexto:"Variante puntual vs Tigres · Corral como referencia única" },
    ],
    gamestates: {
      global: { gan:59, emp:34, per:7  },
      local:  { gan:70, emp:30, per:0  },
      visita: { gan:47, emp:38, per:14 },
    },
    franjasSubs: [
      { franja:"1-15'",  n:1,  imp: 0.00 },
      { franja:"31-45'", n:4,  imp: 1.50 },
      { franja:"46-60'", n:9,  imp: 0.00 },
      { franja:"61-75'", n:20, imp:-0.10 },
      { franja:"76-90'", n:16, imp:-0.12 },
    ],
    heatmap: [
      { tipo:"Ofensivo",  gan:{n:3, imp:0.00}, emp:{n:1, imp:2.00}, per:{n:0, imp:0.00} },
      { tipo:"Medio",     gan:{n:30,imp:-0.13},emp:{n:9, imp:0.44}, per:{n:3, imp:0.00} },
      { tipo:"Defensivo", gan:{n:4, imp:0.00}, emp:{n:0, imp:0.00}, per:{n:0, imp:0.00} },
    ],
    franjasGoles: [
      { f:"1-15'",  gf:6, gc:0, pumGF:0, pumGC:3 },
      { f:"16-30'", gf:3, gc:1, pumGF:4, pumGC:2 },
      { f:"31-45'", gf:8, gc:1, pumGF:5, pumGC:3 },
      { f:"46-60'", gf:8, gc:1, pumGF:1, pumGC:2 },
      { f:"61-75'", gf:4, gc:0, pumGF:2, pumGC:3 },
      { f:"76-90'", gf:6, gc:2, pumGF:1, pumGC:6 },
    ],
    banco: [
      { n:"Paola Garcia",              p:"F",   ent:7, impT: 2, impP: 0.29, rat:6.69, gs:"Ganando"   },
      { n:"Julia Yareli Alvidrez",     p:"M",   ent:6, impT: 0, impP: 0.00, rat:6.82, gs:"Ganando"   },
      { n:"Abril A. Fragoso García",   p:"M/F", ent:4, impT: 0, impP: 0.00, rat:7.18, gs:"Ganando"   },
      { n:"Mackenzee Vance",           p:"M",   ent:4, impT: 0, impP: 0.00, rat:6.85, gs:"Ganando"   },
      { n:"Kelly Caicedo",             p:"D",   ent:4, impT: 0, impP: 0.00, rat:6.83, gs:"Ganando"   },
      { n:"Sydney Becerra",            p:"M/F", ent:3, impT: 0, impP: 0.00, rat:7.17, gs:"Ganando"   },
      { n:"Alexandra Godínez",         p:"D/M", ent:5, impT:-2, impP:-0.33, rat:6.72, gs:"Ganando"   },
      { n:"Andrea Pereira",            p:"M",   ent:1, impT:-2, impP:-2.00, rat:6.30, gs:"Ganando"   },
    ],
    xi: [
      { n:"Esthefanny Barreras",      p:"G", pj:"11/12", rat:7.57, nota:"Titular indiscutible · sólida bajo los tres palos" },
      { n:"Berenice Ibarra Hernández",p:"D", pj:"12/12", rat:7.18, nota:"La única con 12/12 · presencia continua en ambas fases" },
      { n:"Osinachi Ohale",           p:"D", pj:"10/12", rat:6.96, nota:"Zaguera central internacional · lectura táctica elevada" },
      { n:"Yirleidis Quejada Minota", p:"D", pj:"10/12", rat:7.02, nota:"En ascenso (+0.26) · central físico con salida limpia" },
      { n:"Kenti Robles",             p:"D", pj:" 9/12", rat:7.12, nota:"⚑ Lateral que se proyecta · su espalda es el espacio más explotable" },
      { n:"Karla Nieto",              p:"M", pj:"12/12", rat:7.43, nota:"Omnipresente · cubre los dos carrileros laterales" },
      { n:"Nina Nicosia",             p:"M", pj:"12/12", rat:7.74, nota:"⚑ Motor creativo · en caída (-1.07 últimas 3J)" },
      { n:"Andrea Pereira",           p:"M", pj:" 8/12", rat:7.45, nota:"Verticalidad cuando inicia · mejor como titular que suplente" },
      { n:"María Natalia Mauleon",    p:"M", pj:" 7/12", rat:6.90, nota:"⚑ En caída pronunciada (-0.90) · forma baja" },
      { n:"Charlyn Corral",           p:"F", pj:" 9/12", rat:8.49, nota:"⭐ Mejor del torneo · en ascenso (+0.17) · máximo peligro" },
      { n:"Chinwendu Ihezuo",         p:"F", pj:" 5/12", rat:6.85, nota:"Segunda punta · presión alta · comparte con Fragoso" },
    ],
    forma: [
      { n:"Charlyn Corral",           p:"F", prev:8.30, ult:8.47, d:+0.17 },
      { n:"Karla Nieto",              p:"M", prev:7.41, ult:7.46, d:+0.05 },
      { n:"Yirleidis Quejada",        p:"D", prev:6.94, ult:7.20, d:+0.26 },
      { n:"Osinachi Ohale",           p:"D", prev:6.88, ult:7.04, d:+0.16 },
      { n:"Esthefanny Barreras",      p:"G", prev:7.73, ult:7.38, d:-0.35 },
      { n:"Berenice Ibarra",          p:"D", prev:7.24, ult:7.08, d:-0.16 },
      { n:"Kenti Robles",             p:"D", prev:7.15, ult:7.07, d:-0.08 },
      { n:"Andrea Pereira",           p:"M", prev:7.95, ult:7.32, d:-0.63 },
      { n:"María Natalia Mauleon",    p:"M", prev:7.60, ult:6.70, d:-0.90 },
      { n:"Nina Nicosia",             p:"M", prev:8.19, ult:7.12, d:-1.07 },
    ],
    alertas: [
      "Pachuca marca primero en 10/12 partidos — cuando lo logra promedia 2.60 pts/PJ.",
      "Franjas 31-45' y 46-60': concentran 16 de sus 35 goles (46%) — el tramo más letal.",
      "Cambio Ofensivo desde EMPATANDO: impacto +2.00 — su combinación más peligrosa del banco.",
    ],
    hallazgos: [
      "84% de cambios son tipo Medio — Torres gestiona energía, no modifica el sistema.",
      "Cambios en 61-75' GANANDO: impacto -0.13 — el rival se vuelve más vulnerable cuando enfrían el partido.",
      "Nina Nicosia: caída de -1.07 en J8-J10 — el motor creativo no llega en su mejor momento.",
      "Paola Garcia es la única suplente con impacto positivo neto (+0.29) — su ingreso activa el ataque.",
      "J6 vs Tigres (2-2): único empate en casa · modelo con bloque defensivo y contraataque válido para Pumas.",
    ],
    notasSubs: [
      { tipo:"info",   txt:"61-75' concentra el 40% de los cambios — Torres hace rotaciones masivas en esa ventana." },
      { tipo:"info",   txt:"84% de los cambios son tipo Medio — el sistema no cambia independientemente del marcador." },
      { tipo:"alerta", txt:"Cambio Ofensivo desde empate tiene impacto +2.00 — si el partido está igualado al 70', anticipar el ingreso de Paola Garcia." },
      { tipo:"alerta", txt:"Cambios en 76-90' tienen impacto -0.12 — Pachuca pierde rendimiento en el cierre, momento para presionar." },
    ],
    notasGoles: [
      { tipo:"alerta", txt:"Franja 1-15': Pachuca anota 6 GF y Pumas recibe 3 GC — arranque peligroso, bloque compacto obligatorio." },
      { tipo:"alerta", txt:"Franjas 31-45' y 46-60': 16 goles de Pachuca (46% del total) — el tramo de mayor concentración ofensiva." },
      { tipo:"info",   txt:"Franja 76-90': Pumas recibe 6 GC — si el partido llega vivo al 75', el riesgo defensivo es máximo." },
    ],
    notasLV: [
      { tipo:"info",   txt:"Como local: 2.67 pts/PJ · 0 minutos PERDIENDO · 5G-1E-0D — el mejor rendimiento del torneo en casa." },
      { tipo:"info",   txt:"Como visita: 1.83 pts/PJ · 3G-2E-1D — sigue siendo peligroso con 14 GF en 6 partidos." },
      { tipo:"alerta", txt:"Los 3 empates del torneo ocurrieron todos de visita (Tigres J6, Toluca J9, Guadalajara J12) — cuando no marca primero, el resultado se complica." },
    ],
    notasBanco: [
      { tipo:"info",   txt:"Paola Garcia: 7 entradas · única suplente con impacto positivo neto — su ingreso activa la segunda punta." },
      { tipo:"alerta", txt:"Alexandra Godínez y Andrea Pereira como suplentes: impacto negativo (-0.33 y -2.00) — no son amenaza real desde el banco." },
      { tipo:"info",   txt:"Abril Fragoso y Sydney Becerra mantienen rating alto desde el banco (+7.18 y +7.17) — entran preparadas." },
    ],
    notasForma: [
      { tipo:"alerta", txt:"Charlyn Corral (+0.17) llega en su mejor momento del torneo — el peor momento para enfrentarla." },
      { tipo:"alerta", txt:"Nina Nicosia (-1.07) y María Natalia Mauleon (-0.90): el mediocampo creativo en descenso pronunciado." },
      { tipo:"info",   txt:"Yirleidis Quejada (+0.26) y Osinachi Ohale (+0.16): la zaga central llega a su mejor nivel." },
    ],
  },
